Fix building on MacOS. Add new PR check. (#1272)
Fix build step on MacOS and add PR check to avoid deployment surprises.
Use `pip` to install dependencies, because poetry doesn't build wheels.

[`fastecdsa`](https://pypi.org/project/fastecdsa/) can't be installed on
`MacOS11.7.1@20221204.1` but it can be installed on
`MacOS11.7.1@20221121.1` and on `MacOS10.15`. Runner can't be selected
by version only by label (e.g. `macos-11`) and [`MacOS 10.15` runner
should've been removed 1st December
2022](https://github.com/actions/runner-images/issues/5583).

> ERROR: fastecdsa-2.2.3-cp39-cp39-macosx_11_0_x86_64.whl is not a
supported wheel on this platform.